### ISSUE TITLE
Is there a version compatible with Artemis version 1.1.0?

### ISSUE THREAD

**Issue by npeder** [rh-messaging/artemis-hawtio#17]
JBoss EAP 7.0 is bundled with Artemis version 1.1.0.SP16-redhat-1 and it seems the hawtio plugin tries to use some operations that does not exist in this version:

From the hawtio console log:

[Core] Operation sendTextMessage(java.util.Map, java.lang.String, java.lang.String, java.lang.String) failed due to: java.lang.IllegalArgumentException : No operation sendTextMessage found on MBean org.apache.activemq.artemis:address="jms.queue.e_message_status_queue",module=Core,name="jms.queue.e_message_status_queue",type=Queue

**Comment by andytaylor** [comment]
you will need to use 1.3 or later

**Comment by bligny** [comment]
Can you please tell us which previous version (i.e git tag) of artemis-hawtio is compatible with the "old" Artemis 1.1.0 ?
Thx in advance.

**Comment by andytaylor** [comment]
there isnt one, this was developed post 1.3

**Comment by buehlmann** [comment]
Would be nice to use this plugin with Wildfly 10 / EAP 7. Especially for inspecting destinations by webbrowser and not with standalone applications like Hermes JMS..
