### ISSUE TITLE
Where i can get artemis-plugin.war?

### ISSUE THREAD

**Issue by varnav** [rh-messaging/artemis-hawtio#18]
Hello!

Documentation says to place hawtio-web.war and artemis-plugin.war to artemis web directory.
I have downloaded hawtio-web.war from http://hawt.io/getstarted/index.html
Where I can get artemis-plugin.war? Documentation says nothing about that.

**Comment by andytaylor** [comment]
mvn package will create it for you

**Comment by varnav** [comment]
Oops, "apt-get install maven" has broken my java on Debian 8, breaking Artemis. I fixed that, not easy.
That would be cool to have .war downloadable somewhere.
