### ISSUE TITLE
After installing the latest package for artemis-hawtio plugin I can't browse anymore on the queues. 

### ISSUE THREAD

**Issue by der7gfs** [rh-messaging/artemis-hawtio#23]
Before "patch":

![artemishawtio_beforepatch](https://cloud.githubusercontent.com/assets/22912151/20396761/42ac85d2-acb5-11e6-8717-f7bcb15bfac7.PNG)

After "patch":

![artemishawtio_afterpatch](https://cloud.githubusercontent.com/assets/22912151/20396775/4fe82792-acb5-11e6-9f38-02cfb448ba81.PNG)

Thank you

**Comment by der7gfs** [comment]
Forgot to mention I'm using Artemis 1.5.0

**Comment by andytaylor** [comment]
this is a development branch, you should use one of the tags

**Comment by der7gfs** [comment]
not sure what you mean by that...followed the instructions here: https://help.github.com/articles/creating-an-issue/

**Comment by andytaylor** [comment]
I meant that I am developing some new functionality on master so you should use a stable tag

**Comment by der7gfs** [comment]
Oh OK, no problem. Thank you.
