### ISSUE TITLE
Which one is the official artemis-hawtio?

### ISSUE THREAD

**Issue by tadayosi** [rh-messaging/artemis-hawtio#43]
Hi,

I've found that Artemis also has its own codebase of artemis-hawtio:
https://github.com/apache/activemq-artemis/tree/master/artemis-hawtio/artemis-plugin

So now which one is the official and will be maintained?

**Comment by andytaylor** [comment]
upstream

**Comment by tadayosi** [comment]
Does it mean apache/activemq-artemis gh repo?

**Comment by andytaylor** [comment]
sorry I dont understand the question

**Comment by tadayosi** [comment]
OK, so changing the question, what is this artemis-hawtio repository now for?  Is it just a fork of apache/activemq-artemis/tree/master/artemis-hawtio/artemis-plugin for building AMQ 7?  Are you still going to maintain this repository or not?

**Comment by andytaylor** [comment]
its not used for anything, it was until the code was donated to the Artemis project
