### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by kotfilemon** [rh-messaging/artemis-hawtio#9]
can you provide steps to install that plugin on wildfly 10? thank you

What I did:
- ActiveMQ Artemis is configured and running
- I dropped hawtio.war to deployment directory.
- I dropped builded by maven artemis-plugin with name chanaged just to artemis-plugin.war
- I even dropped jolokia.war

I tried with the standalone jar - made a plugin directory and put artemis-plugin.war there. 

when I connect to jolokia I get CPU usage (and stuff like that) for WildFly, I can see, via JMX the queue, but still, to success with Artemis.

hawtio doesnot recognize the plugin however it got loaded:

```
[main] INFO org.eclipse.jetty.webapp.WebAppContext - An Artemis plugin at http://0.0.0.0:8081/artemis-plugin
[main] INFO jetty - Added 3rd party plugin with context-path: /artemis-plugin
Added 3rd party plugin with context-path: /artemis-plugin

```

I donot have 'Artemis' tab. , going to http://0.0.0.0:8081/artemis-plugin shows me the dir:

![image](https://cloud.githubusercontent.com/assets/10028517/17397348/e2dfde6c-5a37-11e6-912e-624c67ad1cac.png)

**Comment by kotfilemon** [comment]
jmx managment has to be switched on:

`<management jmx-enabled="true"/>`

[source](https://developer.jboss.org/thread/271770)

**Comment by andytaylor** [comment]
also the JMX tree has changed between the version in Wildfly and 1.3 so it may not work.

**Comment by andytaylor** [comment]
all the features that is
